environment:
  CMAKE_PATH: c:\projects\JamomaMax\cmake-3.3.0-rc4-win32-x86
  encrypted_key:
    secure: NBgLiSQwqyGpdaFuCaU/pY71Crm4TQ1ClOHJj4cMekk=
  encrypted_iv:
    secure: 8TrT2dUy4RkrNMtaXzhTqEd/SP816Ev/pYdGksosxXA=

configuration: Release

install:
  - appveyor DownloadFile "http://www.cmake.org/files/v3.3/cmake-3.3.0-rc4-win32-x86.zip"
  - 7z x cmake-3.3.0-rc4-win32-x86.zip -y > nul
  - appveyor DownloadFile "http://downloads.sourceforge.net/project/winscp/WinSCP/5.7.5/winscp575.zip?r=&ts=1441560630&use_mirror=freefr"
  - 7z x winscp575.zip -y

platform:
  - Win32
  - x64

before_build:
# - ps: ssh-keyscan -v -t rsa thor.bek.no >> $env:USERPROFILE\.ssh\known_hosts
#  - move /Y %APPVEYOR_BUILD_FOLDER%\script\thor.bek.no.fingerprint  %USERPROFILE%\.ssh\known_hosts
  - ps: openssl aes-256-cbc -K $env:encrypted_key -iv $env:encrypted_iv -in c:\projects\JamomaMax\script\id_rsa-appveyor.enc -out id_rsa -d
  - move /Y id_rsa %USERPROFILE%\.ssh\
  - echo test > test.txt
  - c:\projects\JamomaMax\WinScp.com /command "option batch abort" "open sftp://thor.bek.no/ -privatekey=%USERPROFILE%\.ssh\id_rsa -hostkey=""ssh-rsa 2048 d1:79:9a:fd:b5:8d:f5:5e:ae:05:6d:92:6c:6f:06:ff""" "put test.txt" "exit"
#  - scp -v -o PreferredAuthentications=publickey -i %USERPROFILE%\.ssh\id_rsa test.txt jamomabuild@thor.bek.no:/Volumes/ThorData/WebServer/Jamoma/nanoc-website/output/download/JamomaMax/nightly-builds
#  - scp -v -o PreferredAuthentications=publickey JamomaMax-Windows_* jamomabuild@thor.bek.no:/Volumes/ThorData/WebServer/Jamoma/nanoc-website/output/download/JamomaMax/nightly-builds
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - set CMAKE=%CMAKE_PATH%\bin\cmake.exe
  - if %PLATFORM% == x64 (set CMAKE_GENERATOR="Visual Studio 12 2013 Win64") ELSE (set CMAKE_GENERATOR="Visual Studio 12 2013")
  - if %PLATFORM% == x64 (set CUSTOM_FLAG="-DWIN64:Bool=True") ELSE ( set CUSTOM_FLAG="" )
  - cmake -G%CMAKE_GENERATOR% %CUSTOM_FLAG%  -DCMAKE_INSTALL_PREFIX=%CD%/JamomaInstall -DCMAKE_BUILD_TYPE=Release ..

build:
  parallel: true
  project: C:/projects/jamomamax/build/JamomaMax.sln

after_build:
  - cmake -DBUILD_TYPE=Release -DCMAKE_INSTALL_COMPONENT=JamomaMax -P cmake_install.cmake > nul
  - cd JamomaInstall\JamomaMax
  - 7z a JamomaMax-Windows_%PLATFORM%-%APPVEYOR_REPO_COMMIT:~0,7%-%APPVEYOR_REPO_TAG_NAME%.zip Jamoma > nul
  - move /Y JamomaMax-Windows_*.zip %APPVEYOR_BUILD_FOLDER%

artifacts:
  - name: Jamoma for Max - Windows $(platform)
    path: JamomaMax-*.zip

