environment:
  CMAKE_PATH: c:\projects\JamomaMax\cmake-3.3.0-rc4-win32-x86
  encrypted_key:
    secure: wMFDidPMGaYZm9nzEn9OSoPa2BIRrLw5bpKkvcGJCY8=
  encrypted_iv:
    secure: iXPMeWgtvO5yvxY5yQodIH7+AAZhMjjLIAgUw429d7A=

configuration: Release

#shallow_clone: true # clone repository as zip archive

install:
  - appveyor DownloadFile "http://www.cmake.org/files/v3.3/cmake-3.3.0-rc4-win32-x86.zip"
  - 7z x cmake-3.3.0-rc4-win32-x86.zip -y > nul
  - appveyor DownloadFile "https://cdn.winscp.net/files/winscp575automation.zip?secure=JQL1Tu8k6lIxTic_3fQh6A==,1441994328"
  - 7z x winscp575automation.zip -y

platform:
  - Win32
  - x64

build_script:
  - ps: c:\projects\JamomaMax\script\appveyor.ps1

deploy_script:
  - ps: c:\projects\JamomaMax\script\deploy-appveyor.ps1

artifacts:
  - name: Jamoma for Max - Windows $(platform)
    path: JamomaMax-*.zip
  - name: Log files
    path: c:\projects\JamomaMax\*.log

